version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vinyl-store-mysql
    restart: unless-stopped
    
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vinyl_store
      MYSQL_USER: vinyl_user
      MYSQL_PASSWORD: vinyl_password

    ports:
      - "3307:3306"
    
    volumes:
      - mysql_data:/var/lib/mysql
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - vinyl-store-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vinyl-store-phpmyadmin
    restart: unless-stopped
    
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    
    ports:
      - "8080:80"
    
    depends_on:
      - mysql
    
    networks:
      - vinyl-store-network

volumes:
  mysql_data:
    driver: local

networks:
  vinyl-store-network:
    driver: bridge